version: '3.0'

volumes:
  if-db-data:

services:
  if_dev_web:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    image: vn_dev
    container_name: if_dev_web
    volumes:
      - ./.composer:/var/www/.composer
      - ./src:/var/www/html
    ports:
      - "80:80"

  if_dev_db:
    image: mysql:5.7
    container_name: if_dev_db
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=128M
    ports:
      - "3306:3306"
    volumes:
      - ./databases:/databases
      - if-db-data:/var/lib/mysql
    env_file:
      - ./src/.env
